@url = http://localhost:3010/booking

@bookableCouchId=618791b8-0674-8cec-bcaa-f310da8f5534

@couchBookingRequestId=dece7048-280a-0cb8-a401-926610aca82c

@guestAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ2YWx1ZSI6IjY5YjBkNjViLTNhYjMtMTg3Yy0xZTM4LTk4ZDI5MDJiYTk4YyJ9LCJleHAiOjE2MjAxNDk3NTksImlhdCI6MTYyMDE0Nzk1OX0.X5v8yZj8KL3yGRYs-b-Lxoc-Wm4Zrgz6gJwNWcXwyWc

@hostAccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJ2YWx1ZSI6ImFlZjcxODdlLTgyOWItNzJmYi1iNDczLTZlNDFiNWFmMTkxOSJ9LCJleHAiOjE2MjI5MjU4NzMsImlhdCI6MTYyMjkyNDA3M30.c570z0UpXYG3pcCX2gFsPrKyO-7qVMqZbWKdX5ZBc1k
### 
POST {{url}}/request-booking HTTP/1.1
content-type: application/json
authorization: Bearer {{guestAccessToken}}

{
    "bookableCouchId":"{{bookableCouchId}}",
    "dateFrom": "2021-10-23T00:00:00.000Z",
    "dateTo": "2021-10-25T00:00:00.000Z",
    "quantity": 1
}
### 
POST {{url}}/create-booking HTTP/1.1
content-type: application/json
authorization: Bearer {{hostAccessToken}}

{
    "couchBookingRequestId":"{{couchBookingRequestId}}"
}
### 
POST {{url}}/reject-booking-request HTTP/1.1
content-type: application/json
authorization: Bearer {{hostAccessToken}}

{
    "couchBookingRequestId":"{{couchBookingRequestId}}",
}
### 
POST {{url}}/finish-bookings HTTP/1.1
content-type: application/json
authorization: Bearer {{hostAccessToken}}
### 
POST {{url}}/archive HTTP/1.1
content-type: application/json
authorization: Bearer {{hostAccessToken}}

{
    "bookableCouchId":"{{bookableCouchId}}"
}