@url = http://localhost:3010/user
@email = user2@testing.com

@password = password1234

@userId = c839b40c-7dec-0138-6682-7dbe471c5181
### 
POST {{url}}/register HTTP/1.1
content-type: application/json

{
    "email":"{{email}}",
    "password":"{{password}}"
}

###
GET {{url}}/{{userId}} HTTP/1.1
content-type: application/json
### 
POST {{url}}/login HTTP/1.1
content-type: application/json

{
    "email":"{{email}}",
    "password":"{{password}}"
}