@url = http://localhost:3010/user
@email = user@testing.com

@password = password1234

@userId = ddc30800-f412-a3d7-cc80-4c4a9f6a1b0e
### 
POST {{url}}/register HTTP/1.1
content-type: application/json

{
    "email":"{{email}}",
    "password":"{{password}}"
}

###
GET {{url}}/{{userId}} HTTP/1.1
content-type: application/json
### 
POST {{url}}/login HTTP/1.1
content-type: application/json

{
    "email":"{{email}}",
    "password":"{{password}}"
}
### 
PUT {{url}}/{{userId}} HTTP/1.1
content-type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "location":"London, UK",
    "aboutMe":"Lorem ipsum"
}